language: python
python:
  - "2.7"
# install database service
services:
  - mongodb
# install dependencies
install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install python-setuptools python-dev swig libxmlsec1 xmlsec1 nginx"
  - "pip install -r requirements.txt"

# setup environment and start AMSoil NETCONF
before_script:

  - "cp AMSoil_NETCONF/deploy/config.json.example deploy/config.json"
  - "python AMSoil_NETCONF/src/main.py &"
  - "python AMSoil_NETCONF/src/main_netconf.py &"
  - "sleep 5"

# run Python unit tests
script:
  -  "python AMSoil_NETCONF/test/unit/netconf/netconf_tests.py"

# notify result of build to email address
notifications:
  email:
    - adel.zaalouk@eict.de

